dist: xenial

jdk:
  - openjdk8

language: scala

script: "sbt +clean +coverage +test +coverageReport"

before_script:
- mkdir -p test-dbs/postgres
- sudo chown postgres:postgres test-dbs/postgres/

after_success:
- "sbt coverageAggregate coveralls"

services:
  - mysql
  - postgresql

deploy:
  provider: script
  script: sbt +publish
  on:
    tags: true
